sudo: required
services:
  - docker

before_install:
  - docker build -t pdxc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pdxc/react-test npm test

after_success:
  - docker build -t pdxc/test-multi-client ./client
  - docker build -t pdxc/test-multi-nginx ./nginx
  - docker build -t pdxc/test-multi-server ./server
  - docker build -t pdxc/test-multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the built images to docker hub
  - docker push pdxc/test-multi-client
  - docker push pdxc/test-multi-nginx
  - docker push pdxc/test-multi-server
  - docker push pdxc/test-multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-652826499176
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
